image: Visual Studio 2017
before_build:
  - cmd: dotnet restore library/ref
  - cmd: dotnet restore library/src
  - ps: . .\download_resources.ps1
# build:
#   publish_nuget: true
#   parallel: true
#   verbosity: minimal
build_script:
  - dotnet build library/ref -c Release
  - dotnet build library/src -c OSX_Release
  - dotnet build library/src -c Linux_Release
  - dotnet build library/src -c Windows_Release

after_build:
  - nuget pack library/DotnetWorld.nuspec

artifacts:
  - path: /DotnetWorld*.nupkg/
    name: Nupkg